name: Main Preview

on:
  push:
    branches: [main]

jobs:
  main:
    name: Build and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Setup Node
      uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node-version }}
    - name: Install Packages
      run: npm ci
      shell: bash
    - name: Build Storybook
      run: npx build-storybook
      shell: bash
    - name: Upload to S3
      uses: yandex-cloud/ui-preview-upload-to-s3-action@main
      with:
        src-path: storybook-static
        dest-path: /${{ inputs.project }}/main/
        s3-key-id: ${{ inputs.s3-key-id }}
        s3-secret-key: ${{ inputs.s3-secret-key }}
